### ISSUE TITLE
[VISION] Auth, login & bookmark refactor

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2376]
- [ ] Selective logout #2302
- [ ] Fix login scopes #2165
- [ ] Add PAT to auth #2165
- [ ] Bookmarks
  - [ ] iCloud sync #2377
  - [ ] Sort/reordering/foldering #1886
  - [ ] States to update open/closed icon and title edits #2379
  - [ ] Reflect total count in section header #2441
  - [ ] Integrate with Github’s “save for later” (pending API) #2377
-   [ ] return of search

The following referenced tickets can be closed:
#2379 #2377 #1886 #2441 #2302 #2165

**Comment by ijm8710** [comment]
@rnystrom I would actually perhaps rate this as higher than 2375 because of feasible, and if my analysis on credential ticket is also accurate, this provides a solution without your data loss concern

**Comment by rnystrom** [comment]
Oh interesting. I bet we could bundle all of it in the next update:

- Bookmark sync
- Selective logout
- Fix login scopes
- Add PAT to auth

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Yeah that would be beautiful!

**Comment by ijm8710** [comment]
Hey @rnystrom hopefully a tag and revisit here is ok :)
Do you think this might be a good idea to try to action for 1.25 or 1.26?

**Comment by rnystrom** [comment]
Ya I’d like to get the login enhancements in a future version once the refactor noise quiets down. Can always use help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@rnystrom I laid everything out more condensed and on one ticket. Hopefully you agree this makes it easier to follow

**Comment by rob-nash** [comment]
I found [this repository](https://github.com/intellum/neeman) today by @intellum. It might be useful to you.

Their recent work on this repo has broken two example projects nested in the root dir. So I submitted a PR to get the 'intermediate' example project running. 

Checkout the code [here](https://github.com/intellum/neeman/pull/20) and navigate to Root/Examples/Intermediate and run `carthage bootstrap` there.

![untitled 2018-11-28 16_46_31](https://user-images.githubusercontent.com/14126999/49167454-4a465000-f32d-11e8-9bc1-b79f44617360.gif)

**Comment by ijm8710** [comment]
@rob-nash is that a wrapper of the mobile site or an app?

**Comment by rob-nash** [comment]
@ijm8710 wrapper around WKWebView

**Comment by rnystrom** [comment]
Closing this as its just a summary of already-tracked issues
