### ISSUE TITLE
[VISION] Pull Requests

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2496]
The theme seems to be these [VISION] issues rather than projects. 

I think we can make pull requests awesome in GitHawk, I just want to compile a bunch of scattered issues that are still open that would make this happen.

- [ ] We do not show all PR comments/replies. This means using the app to review pull request is almost impossible after you've passed the limit of the number of comments we show. #1760 
- [ ] Displaying code could be enhanced #2136
- [ ] Add ability to review a PR #2061
- [ ] Add ability to Approve/Disapprove PR's #2137. Possibly in the manager button.
- [ ] Add ability to delete branch after merge #1542
- [ ] Creating a pull request in-app  #1796. We can generalize the new feature banner #2473 and use that to inform users of a possible new pull request to create.

I think compiling related issues is a great idea for productivity. 
Let me know if I missed issues.

**Comment by Sherlouk** [comment]
Random idea, but maybe we could block out the "Merge Pull Request" button if the title has WIP: or something similar in the name? (Something more used on GitLab admittedly but I quite like it)

**Comment by Huddie** [comment]
@Sherlouk maybe have that as an option? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@Sherlouk instead of blocking it out maybe just warn the user “this pull request seems to be marked as a work in progress, are you sure you want to merge”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
> Random idea, but maybe we could block out the "Merge Pull Request" button if the title has WIP: or something similar in the name? (Something more used on GitLab admittedly but I quite like it)

Guess with drafts we do not need this anymore :-)
