### ISSUE TITLE
Inbox Redesign

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2497]
This comes from the #2177 thread. 

Just thoughts on improving the inbox. 

Related Issues:
- [x] ~Updated icons #2177~
- [ ] Possible removal or replacement of speaker icon [reason here](https://github.com/GitHawkApp/GitHawk/issues/2149#issuecomment-418171984) also works well with #2482 
- [ ] Githubs Issue Dashboard feature #2413 which aids in #1265, #2065, #2272
- [ ] Displaying the author #1885
- [ ] Grouping repos in the inbox allowing for additional actions such as read all for a specfic repo etc #2411

We should try to think about #620, this is where we redesigned away from complexity. 
In the past Ryan has thrown a few design out to the twitterverse to see what people liked. I think that makes sense here as well.

@kocheck will hopefully mock up a few designs. If anyone has thoughts or suggestions comment away!

**Comment by Huddie** [comment]
Just a quick update from #2413 to keep things up to date here. 

Ryan suggested using the navigation bar drop down that we see throughout the app in the inbox and when you click it your presented with a context menu where you can select different inbox modes.

Modes being:
- Master list
- Notifications 
- Assigned 
- Mentioned
- etc

A new request would go out with each reload of the inbox since we wouldn’t be doing intense filtering in-app (GitHub’s api allows for a filter parameter)

@rnystrom currently drop down opens action sheet, context menu would be different from the norm.
Do we mind? Do we want to switch all action sheets to context menu (as maybe a later goal)?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Menu would give us a ton more options w/ the UI (icons, selection indicator, section headers, etc)

**Comment by rnystrom** [comment]
Open to considering large titles for inbox too

**Comment by kocheck** [comment]
Design should also consider how issue #2473 would affect this screen as well 👍

**Comment by ijm8710** [comment]
Just make sure you’re on latest TF as some of the OP has changed :)

**Comment by kocheck** [comment]
Nice! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kocheck** [comment]
Reading through all the additional issues and taking notes to make some soft design requirements. I have a question for whomever it may concern. ✌️

Reading through the issues I have an idea to make the inbox more flexible for different workflows. How do you folks feel about allowing the user to choose what mode should be default in the inbox?
So for me, I like to have a repo overview. It looks like some people like to see what they are assigned and what they are subscribed to. 

Does that make any sense? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Makes sense to me @kocheck

**Comment by ijm8710** [comment]
Would it make potential sense to have the repos drop down list both starred repos in addition to watched repos. Or would you want those just moreso accessible from revised wireframes profiles in #?

**Comment by kocheck** [comment]
I like that idea @ijm8710  Do you think we would need some sort of search feature then? I know for some users that I have seen, the Stars list gets quite long.

**Comment by ijm8710** [comment]
That or a scroller wouldn’t hurt if that’s the case

**Comment by Huddie** [comment]
@kocheck There is actually an issue that requests the search in the context-menu feature. I think search is a good addition

**Comment by kocheck** [comment]
Oh I will add that to my wireframes then. I think that could be useful in the long run.
